# Generated by Django 5.0.1 on 2024-04-14 20:54

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_title", models.CharField(max_length=50, unique=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ManufacturerPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_title", models.CharField(max_length=50, unique=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("hero_bkgd_img", models.CharField(blank=True, max_length=200)),
                ("article_subtitle", models.CharField(blank=True, max_length=200)),
                ("content", django_summernote.fields.SummernoteTextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_description", models.CharField(max_length=200)),
                ("footer_description", models.CharField(max_length=200)),
                ("site_logo", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("yelp_link", models.CharField(max_length=200)),
                ("instagram_link", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Site Info",
            },
        ),
        migrations.CreateModel(
            name="HomeHeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bkgd_img", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(max_length=200)),
                ("btn_text", models.CharField(max_length=200)),
                ("btn_link", models.CharField(max_length=200)),
                (
                    "home_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_data.homepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=200)),
                (
                    "manufacturer_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_data.manufacturerpage",
                    ),
                ),
            ],
        ),
    ]
