# Generated by Django 5.0.1 on 2024-01-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="slug",
            field=models.SlugField(default="page", unique=True),
            preserve_default=False,
        ),
    ]
