# Generated by Django 5.0.1 on 2024-01-26 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_data", "0002_page_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="title",
            new_name="html_title",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="slug",
            new_name="url_slug",
        ),
    ]
