# Generated by Django 5.0.1 on 2024-01-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_data", "0003_rename_title_page_html_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="hero_bkgd_img",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
