# Generated by Django 5.0.1 on 2024-04-18 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_data", "0003_homeherosection_heading"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeExpertSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("caption", models.CharField(max_length=200)),
                ("icon", models.CharField(max_length=50)),
                (
                    "home_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_data.homepage",
                    ),
                ),
            ],
        ),
    ]
