# Generated by Django 5.0.1 on 2024-01-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_data", "0004_page_hero_bkgd_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="hero_bkgd_img",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
