# Generated by Django 5.0.1 on 2024-01-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_data", "0006_alter_page_hero_bkgd_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_description", models.CharField(max_length=200)),
                ("site_logo", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
            ],
        ),
    ]
