# Generated by Django 5.0.1 on 2024-01-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_data", "0009_remove_page_content_alter_siteinfo_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="url_slug",
        ),
        migrations.AddField(
            model_name="page",
            name="page_title",
            field=models.CharField(default="ferrari", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
