# Generated by Django 5.0.1 on 2024-01-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_data", "0011_manufacturerpage_article_subtitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=200)),
                (
                    "manufacturer_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_data.manufacturerpage",
                    ),
                ),
            ],
        ),
    ]
