# Generated by Django 5.0.1 on 2024-03-31 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_data", "0012_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="html_title",
        ),
    ]
