# Generated by Django 5.0.1 on 2024-04-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_data", "0013_remove_page_html_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="instagram_link",
            field=models.CharField(
                default="https://www.instagram.com/european_auto_reseda/",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteinfo",
            name="yelp_link",
            field=models.CharField(
                default="https://www.yelp.com/biz/european-auto-service-reseda",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
