# Generated by Django 5.0.1 on 2024-04-05 16:41

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_data", "0014_siteinfo_instagram_link_siteinfo_yelp_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturerpage",
            name="content",
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
